VNet:
  need_bias: True
  in_channels: 1
  out_channels: 3
  deep_supervision: True
  need_features: False
  features: [32, 64, 128, 256, 320, 320]
  dropout_p: [0., 0., 0., 0.3, 0.4, 0.5]
  num_conv_per_stage: [2, 2, 2, 2, 2, 2]
  kernel_size: [[1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
  pool_kernel_size: [[1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]]
  normalization: InstanceNorm
  activate: leakyrelu

DFUNet:
  need_bias: True
  in_channels: 1
  context_in_channels: 2
  out_channels: 3
  context_split: 1
  deep_supervision: True
  need_features: False
  features: [32, 64, 128, 256, 320, 320]
  dropout_p: [0., 0., 0., 0.3, 0.4, 0.5]
  num_conv_per_stage: [2, 2, 2, 2, 2, 2]
  kernel_size: [[1, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3], [3, 3, 3]]
  pool_kernel_size: [[1, 2, 2], [2, 2, 2], [2, 2, 2], [2, 2, 2], [1, 2, 2]]
  normalization: InstanceNorm
  activate: leakyrelu
